# Makefile

# Comando para instalar dependencias
install:
	go mod tidy

# Comando para ejecutar el servidor
run:
	go run cmd/server/main.go

# Comando para construir el proyecto
build:
	go build -o go-hexagonal-starter cmd/server/main.go
